workoutPlanner/exercises/urls.py
from django.urls import path, include

from workoutPlanner.exercises import views

app_name = 'exercises'

urlpatterns = [
    path('add_exercise/', views.AddExerciseView.as_view(), name='add_exercise'),
    path('details/', include([
        path('<slug:slug>/', views.ExerciseDetailView.as_view(), name='exercise_details'),
    ])),
    path('<str:category>/', views.ExerciseListView.as_view(), name='exercise_list'),
]

workoutPlanner/urls.py
from django import core
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('workoutPlanner.forum.api_urls')),
    path('', include([
        path('', include('workoutPlanner.common.urls')),
        path('accounts/', include('workoutPlanner.accounts.urls')),
        path('exercises/', include('workoutPlanner.exercises.urls')),
        path('workouts/', include('workoutPlanner.workouts.urls')),
        path('forum/', include('workoutPlanner.forum.urls')),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workoutPlanner/workouts/urls.py
from django.urls import path, include

from workoutPlanner.workouts import views

app_name = 'workouts'

urlpatterns = [
    path('', views.PredefinedWorkoutListView.as_view(), name='predefined_workout_list'),
    path('create_workout/', views.CreatePredefinedWorkoutView.as_view(), name='create_predefined_workout'),
    path('create_custom_workout/<slug:slug>/', views.CreateCustomWorkoutView.as_view(), name='create_custom_workout'),
    path('update_workout/', include([
        path('<slug:slug>/', views.CustomWorkoutUpdateView.as_view(), name='update_workout'),
    ])
    ),
    path('custom/', include([
        path('', views.CustomWorkoutListView.as_view(), name='custom_workouts_list'),
        path('remove_exercise/<int:pk>/', views.DeleteCustomWorkoutExerciseView.as_view(), name='remove_exercise'),
        path('<slug:slug>/', include([
            path('', views.CustomWorkoutDetailView.as_view(), name='custom_workout_detail'),
            path('delete/', views.CustomWorkoutDeleteView.as_view(), name='custom_workout_delete'),
        ])),
    ])),
    path('<slug:slug>/', views.PredefinedWorkoutDetailView.as_view(), name='predefined_workout_detail'),
]

workoutPlanner/exercises/models.py
from django.db import models
from django.utils.text import slugify

from workoutPlanner.exercises.choices import MuscleGroupChoices


class ExerciseModel(models.Model):
    class Meta:
        app_label = 'exercises'
        db_table = 'exercises_exercisemodel'

    name = models.CharField(max_length=255)

    overview = models.TextField()
    technique = models.TextField()
    muscle_groups = models.CharField(
        max_length=2,
        choices=MuscleGroupChoices
    )
    image = models.ImageField(upload_to='exercises_images/')
    slug = models.SlugField(
        unique=True,
        max_length=255,
        blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

workoutPlanner/exercises/forms.py
from django import forms

from workoutPlanner.exercises.models import ExerciseModel


class AddExerciseForm(forms.ModelForm):
    class Meta:
        model = ExerciseModel
        exclude = ['slug']

workoutPlanner/exercises/views.py
from lib2to3.fixes.fix_input import context

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, DeleteView

from workoutPlanner.exercises.forms import AddExerciseForm
from workoutPlanner.exercises.models import ExerciseModel



class ExerciseDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = ExerciseModel
    template_name = 'exercises/exercise_details.html'
    context_object_name = 'exercise'

class ExerciseListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'exercises/exercises_list.html'
    context_object_name = 'exercises'

    def get_queryset(self):
        category = self.kwargs.get('category')
        return ExerciseModel.objects.filter(muscle_groups__exact=category)



class AddExerciseView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    form_class = AddExerciseForm
    template_name = 'exercises/add_exercise.html'

    def form_valid(self, form):
        exercise = form.save()
        return redirect('exercises:exercise_details', kwargs={'slug': exercise.slug})

    

templates/exercises/add_exercise.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <div class="add-exercise-form-container">
        <h1>Add new exercise</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="submit-btn">Add</button>
        </form>
    </div>
{% endblock %}

templates/exercises/exercise_details.html
{% extends 'base.html' %}
{% load markdown_text %}

{% block title %}{{ exercise.name }}{% endblock %}

{% block content %}
    <div class="exercise-header-container">
        <div class="exercise-title">
            <h1>{{ exercise.name }}</h1>
            <p>Muscle groups: {{ exercise.get_muscle_groups_display }}</p>
        </div>
    </div>
    <div class="exercise-data">
        <div class="exercise-overview">
            <h2>Overview</h2>
            <p>{{ exercise.overview }}</p>
        </div>
        {% if exercise.image %}
            <img src="{{ exercise.image.url }}" alt="{{ exercise.name }}">
        {% else %}
            <p><em>No image available for this exercise.</em></p>
        {% endif %}
        <div class="exercise-article">
            <h2>Technique Description</h2>
            <p>{{ exercise.technique|markdown }}</p>
        </div>
    </div>

{% endblock %}

templates/exercises/exercises_list.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    {% if exercises %}
        {% for exercise in exercises %}
            <div class="exercise-container">
                <div class="exercise-info">
                    <h3>{{ exercise.name }}</h3>
                    <p><span style="font-weight: bold">Primary Muscles:</span> {{ exercise.get_muscle_groups_display }}</p>
                </div>
                <img src="{{ exercise.image.url }}" alt="Image displaying a person doing {{ exercise.name }}">
                <div class="button-container">
                    <a href='{% url 'exercises:exercise_details' slug=exercise.slug %}' class="details-btn" >View Details</a>
                    <a href="{% url 'workouts:create_custom_workout' slug=exercise.slug %}"
                       class="add-btn" >Create new workout
                    </a>
                    <a href="{% url 'workouts:custom_workouts_list' %}"
                       class="add-btn" >Add to existing
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>There is no exercises to display.</p>
        <a href="{% url 'exercises:add_exercise' %}">Add exercise</a>
    {% endif %}
{% endblock %}