workoutPlanner/urls.py
from django import core
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('workoutPlanner.forum.api_urls')),
    path('', include([
        path('', include('workoutPlanner.common.urls')),
        path('accounts/', include('workoutPlanner.accounts.urls')),
        path('exercises/', include('workoutPlanner.exercises.urls')),
        path('workouts/', include('workoutPlanner.workouts.urls')),
        path('forum/', include('workoutPlanner.forum.urls')),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workoutPlanner/workouts/urls.py
from django.urls import path, include

from workoutPlanner.workouts import views

app_name = 'workouts'

urlpatterns = [
    path('', views.PredefinedWorkoutListView.as_view(), name='predefined_workout_list'),
    path('create_workout/', views.CreatePredefinedWorkoutView.as_view(), name='create_predefined_workout'),
    path('create_custom_workout/<slug:slug>/', views.CreateCustomWorkoutView.as_view(), name='create_custom_workout'),
    path('update_workout/', include([
        path('<slug:slug>/', views.CustomWorkoutUpdateView.as_view(), name='update_workout'),
    ])
    ),
    path('custom/', include([
        path('', views.CustomWorkoutListView.as_view(), name='custom_workouts_list'),
        path('remove_exercise/<int:pk>/', views.DeleteCustomWorkoutExerciseView.as_view(), name='remove_exercise'),
        path('<slug:slug>/', include([
            path('', views.CustomWorkoutDetailView.as_view(), name='custom_workout_detail'),
            path('delete/', views.CustomWorkoutDeleteView.as_view(), name='custom_workout_delete'),
        ])),
    ])),
    path('<slug:slug>/', views.PredefinedWorkoutDetailView.as_view(), name='predefined_workout_detail'),
]

workoutPlanner/workouts/models.py
from django.core.serializers import serialize
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.text import slugify

from workoutPlanner.accounts.models import Profile
from workoutPlanner.exercises.models import ExerciseModel
from workoutPlanner.validators import AlphaNumericValidator
from workoutPlanner.workouts.choices import FitnessLevelChoices, TrainingTypeChoices


class CustomWorkoutModel(models.Model):
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name="custom_workouts",
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True,
        max_length=150,
        blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class CustomWorkoutExerciseModel(models.Model):

    workout = models.ForeignKey(
        CustomWorkoutModel,
        on_delete=models.CASCADE,
        related_name='custom_exercises',
    )
    exercise = models.ForeignKey(
        ExerciseModel,
        on_delete=models.CASCADE,
        related_name='custom_exercises',
    )
    sets = models.PositiveSmallIntegerField()
    reps = models.PositiveSmallIntegerField()
    rest = models.PositiveSmallIntegerField()


class PredefinedWorkoutModel(models.Model):
    name = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(2),
        ])
    image = models.ImageField(
        default='workouts_images/default_workout.jpg',
        upload_to='workouts_images/',
    )
    slug = models.SlugField(
        unique=True,
        max_length=150,
        blank=True)
    exercises = models.ManyToManyField(
        ExerciseModel,
    )
    level = models.CharField(max_length=2,
                             choices=FitnessLevelChoices,
                             default=None)
    training_type = models.CharField(max_length=3,
                                     choices=TrainingTypeChoices,
                                     )
    overview = models.TextField()
    content = models.TextField()
    workout_manual = models.TextField()
    effects = models.TextField()
    extra_info = models.TextField(blank=True,  null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

workoutPlanner/workouts/forms.py
from django import forms
from django.forms import inlineformset_factory

from workoutPlanner.workouts.models import PredefinedWorkoutModel, CustomWorkoutModel


class PredefinedWorkoutCreationForm(forms.ModelForm):
    class Meta:
        model = PredefinedWorkoutModel
        exclude = ['slug']
        widgets = {}

class CustomWorkoutCreationForm(forms.ModelForm):
    class Meta:
        model = CustomWorkoutModel
        fields = ['name']
        widgets={
            'name': forms.TextInput(attrs={'placeholder': 'Workout name'}),
        }
        labels={'name':''
        }

workoutPlanner/workouts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from workoutPlanner.exercises.models import ExerciseModel
from workoutPlanner.workouts.forms import PredefinedWorkoutCreationForm, CustomWorkoutCreationForm
from workoutPlanner.workouts.formsets import CustomWorkoutExerciseFormSet, UpdateCustomWorkoutExerciseFormSet
from workoutPlanner.workouts.models import PredefinedWorkoutModel, CustomWorkoutModel, CustomWorkoutExerciseModel


class PredefinedWorkoutBaseView:
    model = PredefinedWorkoutModel
    context_object_name = 'workout'


class PredefinedWorkoutDetailView(LoginRequiredMixin, PredefinedWorkoutBaseView, DetailView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'workouts/predefined_workout_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exercises = context['workout'].exercises.all()
        context['exercises'] = exercises
        return context


class PredefinedWorkoutListView(LoginRequiredMixin, PredefinedWorkoutBaseView, ListView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'workouts/workouts_list.html'
    context_object_name = 'workouts'


class CreatePredefinedWorkoutView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    form_class = PredefinedWorkoutCreationForm
    template_name = 'workouts/create_predefined_workout.html'
    success_url = reverse_lazy('workouts:predefined_workout_list')


class CreateCustomWorkoutView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = CustomWorkoutModel
    form_class = CustomWorkoutCreationForm
    template_name = 'workouts/create_custom_workout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Prepopulate formset exercise field
        formset = CustomWorkoutExerciseFormSet
        exercise_slug = self.kwargs['slug']

        if exercise_slug:
            preselected_exercise = get_object_or_404(ExerciseModel, slug=exercise_slug)
            initial_data = [{'exercise': preselected_exercise}]
        else:
            initial_data = []

        if self.request.POST:
            context['formset'] = formset(self.request.POST)
        else:
            context['formset'] = formset(initial=initial_data)

        return context

    def get_success_url(self):
        return reverse_lazy('workouts:custom_workouts_list')

    def form_valid(self, form):
        # Associate the workout with the user's profile
        profile = self.request.user.profile
        form.instance.profile_id = profile.user_id

        # Save the main form (the workout instance)
        response = super().form_valid(form)

        formset = CustomWorkoutExerciseFormSet(
            self.request.POST,
            instance=self.object,
            )

        if formset.is_valid():
            for form in formset:
                if form.cleaned_data:
                    custom_exercise = form.save(commit=False)
                    custom_exercise.exercise = form.cleaned_data['exercise']
                    custom_exercise.save()

        return response


class CustomWorkoutDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'workouts/custom_workout_details.html'
    context_object_name = 'workout'

    def get_queryset(self):
        # CustomWorkout objects for the logged-in user's profile
        profile = self.request.user.profile
        return CustomWorkoutModel.objects.filter(profile=profile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['custom_exercises'] = CustomWorkoutExerciseModel.objects.filter(workout=self.object)
        return context


class CustomWorkoutListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    template_name = 'workouts/custom_workouts_list.html'
    context_object_name = 'workouts'

    def get_queryset(self):
        return CustomWorkoutModel.objects.filter(profile_id=self.request.user.id)

class DeleteCustomWorkoutExerciseView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('accounts:login')
    model = CustomWorkoutExerciseModel
    template_name = 'workouts/delete-custom-workout-exercise.html'

    def get_success_url(self):
        return reverse_lazy('workouts:custom_workout_detail', kwargs={'slug': self.object.workout.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['custom_exercise'] = CustomWorkoutExerciseModel.objects.get(pk=self.object.pk)
        return context

class CustomWorkoutUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = CustomWorkoutModel
    template_name = 'workouts/update_workout.html'
    form_class = CustomWorkoutCreationForm

    def get_initial(self):
        initial_data = {'name': self.object}
        return initial_data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        formset = UpdateCustomWorkoutExerciseFormSet
        context['formset'] = formset(self.request.POST or None)

        return context


    def get_success_url(self):
        return reverse_lazy('workouts:custom_workouts_list')

    def form_valid(self, form):
        profile = self.request.user.profile
        form.instance.profile = profile
        response = super().form_valid(form)

        formset = UpdateCustomWorkoutExerciseFormSet(self.request.POST)

        if formset.is_valid():
            for form in formset:
                custom_exercise = form.save(commit=False)
                if form.cleaned_data:
                    exercise = form.cleaned_data['exercise']
                    custom_exercise.exercise = exercise
                    custom_exercise.workout = self.object
                    form.save()
        return response


class CustomWorkoutDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('accounts:login')
    form_class = CustomWorkoutCreationForm
    success_url = reverse_lazy('workouts:custom_workouts_list')
    context_object_name = 'workout'
    template_name = 'workouts/delete_custom_workout.html'

    def get_initial(self):
        initial_data = {'name': self.object.name}
        return initial_data

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['name'].disabled = True
        return form

    def get_queryset(self):
        return CustomWorkoutModel.objects.filter(profile_id=self.request.user.id)

templates/workouts/create_custom_workout.html
{% extends 'base.html' %}

{% block title %}Create your workout{% endblock %}

{% block content %}
    <div class="custom-workout-form-container">
        <h1>Create a Workout</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                {{ formset.management_form }}
                
                <table>
                    {% for form in formset %}
                        <tr>
                            {{ form.as_p }}
                        </tr>
                    {% endfor %}
                </table>
                
                <button type="submit">Save Workout</button>
            </form>
    </div>
{% endblock %}

templates/workouts/create_predefined_workout.html
{% extends 'base.html' %}

{% block title %}Add a workout{% endblock %}

{% block content %}
    <div class="predefined-workout-form-container">
        <h1>Workout data</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="submit-btn">CREATE</button>
            <button class="cancel-btn" type="reset"><a href="{% url 'workouts:predefined_workout_list' %}" class="cancel-btn">Cancel</a></button>
        </form>
    </div>
{% endblock %}

templates/workouts/custom_workout_details.html
{% extends 'base.html' %}

{% block title %}{{ workout.name }}{% endblock %}

{% block content %}
    <div class="cw-container">
        <h1>{{ workout.name }}</h1>
        <div class="btn-container">
            <a href="{% url 'workouts:update_workout' slug=workout.slug %}" class="cw-add-btn">Add exercise</a>
        </div>
        <div class="workout-data">
            {% for custom_exercise in custom_exercises %}
                <div class="cw-exercise">
                    <img src="{{ custom_exercise.exercise.image.url }}" height="120px;" width="auto;">
                    <h4>{{ custom_exercise.exercise.name }}</h4>
                    <p><span>Sets:</span> {{ custom_exercise.sets }}</p>
                    <p><span>Reps: </span> {{ custom_exercise.reps }}</p>
                    <p><span>Rest: </span> {{ custom_exercise.rest }}</p>
                    <a href="{% url 'workouts:remove_exercise' pk=custom_exercise.pk %}" class="cw-remove-btn">Remove exercise</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/workouts/custom_workouts_list.html
{% extends 'base.html' %}

{% block title %}Workouts{% endblock %}

{% block content %}
    <div class="custom-workout-wrapper">
        <h1>Your workouts</h1>
        <div class="custom-workout-list">
            {% if workouts %}
                {% for workout in workouts %}
                    <div class="custom-workout-container">
                        <h2>{{ workout.name }}</h2>
                        <a href="{% url 'workouts:custom_workout_detail' slug=workout.slug %}" class="workout-details-btn">View details</a>
                        <a href="{% url 'workouts:custom_workout_delete' slug=workout.slug %}" class="workout-delete-btn">Delete</a>
                    </div>
                {% endfor %}
            {% else %}
                    <p>There are no workouts yet!</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/workouts/delete-custom-workout-exercise.html
{% extends 'base.html' %}

{% block title %}Remove exercise{% endblock %}

{% block content %}
    <div class="delete-post-form-container">
        <h1>Are you sure removing this exercise ?</h1>
        <h2 style="text-align: center; padding-bottom: 30px;">{{ custom_exercise.exercise.name }}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="delete-post-btn">Remove</button>
        </form>
    </div>
{% endblock %}

templates/workouts/delete_custom_workout.html
{% extends 'base.html' %}

{% block title %}Delete {{ workout.name }}{% endblock %}

{% block content %}
    <div class="deletion-form-container">
        <h2>Delete {{ workout.name }}</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn">Delete</button>
            <button class="btn" type="reset">Cancel</button>
        </form>
    </div>
{% endblock %}

templates/workouts/predefined_workout_details.html
{% extends 'base.html' %}
{% load markdown_text %}

{% block title %}{{ workout.name }}{% endblock %}

{% block content %}
    <div class="workout-name">
        <h1 style="text-align: center; font-size: 40px;border-bottom: 1px solid black">{{ workout.name }}</h1>
    </div>
    <div class="workout-info" style="text-align: center;margin: 50px auto; font-size: 20px">{{ workout.overview|markdown }}</div>

    <div class="exercise-list">
        {% if exercises %}
            {% for exercise in exercises %}
                <div class="exercise-predefined-workout">
                    <div class="pw-exercise-info">
                        <p>Exercise {{ forloop.counter }}</p>
                        <p style="font-weight: 500">{{ exercise.name }}</p>
                    </div>
                    <img style="height: 100px;width: auto;" src="{{ exercise.image.url }}"
                         alt="Image displaying a person demonstrating {{ exercise.name }}">
                </div>
            {% endfor %}
            <div class="workout-info">
                <p><span style="font-size: 30px; font-weight: 500; margin-bottom: 30px">Workout content</span></p>
                {{ workout.content|markdown }}
            </div>
            <div class="workout-info">
                <p><span style="font-size: 30px; font-weight: 500; margin-bottom: 30px">Workout manual</span></p>
                {{ workout.workout_manual|markdown }}
            </div>
            <div class="workout-info">
                <p><span style="font-size: 30px; font-weight: 500; margin-bottom: 30px">Workout effects</span></p>
                {{ workout.effects|markdown }}
            </div>
            {% if workout.extra_info %}
                <div class="workout-info">
                    <p><span style="font-size: 30px; font-weight: 500; margin-bottom: 30px">Workout extra information</span></p>
                    {{ workout.extra_info }}</div>
            {% endif %}
        {% else %}
            <p>There are no exercises yet.</p>
        {% endif %}
    </div>
{% endblock %}

templates/workouts/update_workout.html
{% extends 'base.html' %}

{% block title %}Update your workout{% endblock %}

{% block content %}
    <div class="custom-workout-form-container">
    <h1>Update your workout</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        
        <table>
            {% for form in formset %}
                <tr>
                    {{ form.as_p }}
                </tr>
            {% endfor %}
        </table>
        
        <button type="submit">Save changes</button>
    </form>
    </div>
{% endblock %}

templates/workouts/workouts_list.html
{% extends 'base.html' %}

{% block title %}Workouts{% endblock %}

{% block content %}
    <div class="workouts-wrapper">
        {% if workouts %}
            {% for workout in workouts %}
                <div class="workout-container">
                    <img src="{{ workout.image.url }}" alt="" style="width: 100px; height: auto;">
                    <p style="font-size: 24px;font-weight: 500">This is {{ workout.name }}</p>
                    <p><span style="font-size: 20px">Level:</span> <span style="color: #bb0200;font-size: 20px;">{{ workout.get_level_display }}</span></p>
                    <a href="{% url 'workouts:predefined_workout_detail' slug=workout.slug %}" class="details-btn" style="width: 80px;height: 30px; text-align: center">Details</a>
                </div>

            {% endfor %}
        {% else %}
            <p style="text-align: center; padding: 20px 0; font-size: 40px;">There are no workouts yet!</p>
        {% endif %}
    </div>
{% endblock %}