workoutPlanner/accounts/urls.py
from django.urls import path, include

from workoutPlanner.accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('<int:pk>/', include([
        path('delete_account/', views.UserDeleteView.as_view(), name='delete_account'),
        path('profile-details/', views.ProfileDetailView.as_view(), name='profile-details' ),
        path('update_profile/', views.ProfileUpdateView.as_view(), name='update_profile'),
        path('configure-profile/', views.ProfileConfView.as_view(), name='configure-profile'),
        ])
    )
]

workoutPlanner/common/urls.py
from django.urls import path

from workoutPlanner.common import views

app_name = 'common'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

workoutPlanner/forum/urls.py
from django.urls import path, include

from workoutPlanner.forum import views
from workoutPlanner.forum.views import PostListCreateAPIView

app_name = 'forum'
urlpatterns = [
    path('', include([
        path('', views.PostListView.as_view(), name='post_list'),
        path('<int:pk>/', include([
            path('', views.PostDetailView.as_view(), name='post_detail'),
            path('edit/', views.PostUpdateView.as_view(), name='post_update'),
            path('delete/', views.PostDeleteView.as_view(), name='post_delete'),
            path('comment/', views.AddCommentView.as_view(), name='add_comment'),
        ])),
    ])),

]

workoutPlanner/urls.py
from django import core
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('workoutPlanner.forum.api_urls')),
    path('', include([
        path('', include('workoutPlanner.common.urls')),
        path('accounts/', include('workoutPlanner.accounts.urls')),
        path('exercises/', include('workoutPlanner.exercises.urls')),
        path('workouts/', include('workoutPlanner.workouts.urls')),
        path('forum/', include('workoutPlanner.forum.urls')),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workoutPlanner/workouts/urls.py
from django.urls import path, include

from workoutPlanner.workouts import views

app_name = 'workouts'

urlpatterns = [
    path('', views.PredefinedWorkoutListView.as_view(), name='predefined_workout_list'),
    path('create_workout/', views.CreatePredefinedWorkoutView.as_view(), name='create_predefined_workout'),
    path('create_custom_workout/<slug:slug>/', views.CreateCustomWorkoutView.as_view(), name='create_custom_workout'),
    path('update_workout/', include([
        path('<slug:slug>/', views.CustomWorkoutUpdateView.as_view(), name='update_workout'),
    ])
    ),
    path('custom/', include([
        path('', views.CustomWorkoutListView.as_view(), name='custom_workouts_list'),
        path('remove_exercise/<int:pk>/', views.DeleteCustomWorkoutExerciseView.as_view(), name='remove_exercise'),
        path('<slug:slug>/', include([
            path('', views.CustomWorkoutDetailView.as_view(), name='custom_workout_detail'),
            path('delete/', views.CustomWorkoutDeleteView.as_view(), name='custom_workout_delete'),
        ])),
    ])),
    path('<slug:slug>/', views.PredefinedWorkoutDetailView.as_view(), name='predefined_workout_detail'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="{% static 'js/logout.js' %}" type="module"></script>
    <script src="{% static 'js/auto_populate_calories_field.js' %}" type="module"></script>
    <script src="{% static 'js/addPost.js' %}" type="module"></script>
  <script src="{% static 'js/setUpDeleteButtons.js' %}" type="module"></script>
{#    <link href="{% static 'css/forum.css' %}" rel="stylesheet">#}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="/media/favicon-16x16.png" style="border-radius: 10px;">
  </head>
  <body>
    {% include 'nav.html' %}
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    
    {% include 'footer.html' %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/74118e34f1.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
{% load static %}

<footer class="footer-container">
    <div class="footer-second-section">
        <p>© 2024 Workout Planner</p>
    </div>
</footer>

templates/home-page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <section class="home-first">
        <div class="home-top-section-content">
            <h2>Get fit & <span style="color: rgba(53,216,93,0.95); padding-left: 152px;">healthy</span></h2>
            <p>Empower Your Journey, Transform Your Life.</p>
            {% if not user.is_authenticated %}
                <a class="home-first-btn" href="{% url 'accounts:register' %}">Get Started</a>
            {% endif %}
        </div>
    </section>
    <section class="home-second">
        <div class="article">
            <h2>What is WorkoutPlanner all about ?</h2>
            <p>The workout planner is an online tool designed to
                help you create a personalized workout plan based on
                the equipment you have and your fitness preferences.
                If you feel that building your own workout plan is challenging,
                don’t worry—we’re here to guide you through the process, step-by-step,
                and make it easier than ever!</p>
        </div>
        <div class="second-article">
            <div class="hs-container">
                <div class="hs-element">
                    <i class="fa-solid fa-person-running"></i>
                    <div>
                        <h3>Learn how to do the exercises</h3>
                        <p>Not sure about an exercise? The exercise library offers resources to guide you on proper form
                        and technique.</p>
                    </div>
                </div>    
                <div class="hs-element">
                    <i class="fa-regular fa-note-sticky"></i>
                    <div>
                        <h3>Create a free personalized workout</h3>
                        <p>Build a workout plan that fits your goals and preferences.
                        Easily add or remove exercises to create a workout designed specifically by and for you.
                        It's completely free!</p>
                    </div>
                </div>
                <div class="hs-element">
                    <i class="fa-solid fa-dumbbell"></i>
                    <div>
                        <h3>Create custom workouts for your students</h3>
                        <p>Design free custom workout plans for your students.
                        Tailor each educational plan to your student's needs and goals.</p>
                    </div>
                </div>
                <div class="hs-element">
                    <i class="fa-solid fa-calculator"></i>
                    <div>
                        <h3>Fitness Calculators</h3>
                        <p>Track calories, calculate rep maxes, and monitor body composition – all within the app.</p>
                    </div>
                </div>
            </div>
            <img src="../media/second-section-home-article-img.jpg" alt="Fit man standing with phone in the hand.">
        </div>
    </section>
{% endblock %}

templates/nav.html
{% load static %}
{% load custom_filters%}

<nav class="nav-container">
    <div class="logo-container">
        <a href="{% url 'common:home' %}"><img class="logo" src="{% static 'media/images/logo.jpg' %}" alt="The logo of this website."></a>
    </div>
    <div class="nav-bar">
        <div class="drop-btn">
            <a href="{% url 'common:home' %}" class="drop-btn">HOME</a>
        </div>
        
        <div class="drop-btn">
            <a href="{% url 'forum:post_list' %}" class="drop-btn">FORUM</a>
        </div>    
        
        <div class="nav-dropdown-container">
            <div class="drop-btn">
                <a href="{% url 'workouts:predefined_workout_list' %}" class="drop-btn">WORKOUTS</a>
            </div>
            {% if user|has_perm:'workouts.add_predefinedworkoutmodel' %}
                <div class="nav-dropdown-content">
                    <a href="{% url 'workouts:create_predefined_workout' %}">Add a workout</a>
                </div>
            {% endif %}
        </div>    
        
{#        <div class="nav-dropdown-container">#}
{#            <div class="drop-btn">#}
{#                <a href="#" class="drop-btn">CALCULATORS</a>#}
{#            </div>    #}
{#            <div class="nav-dropdown-content">#}
{#                <a href="#">Body Mass Index</a>#}
{#                <a href="#">Body Fat Index</a>#}
{#            </div>#}
{#        </div>    #}

        <div class="nav-dropdown-container">
            <div class="drop-btn">
                <a href="#" class="drop-btn">EXERCISES</a>
            </div>    
            <div class="nav-dropdown-content">
                {% if user|has_perm:'exercises.add_exercisemodel' %}
                    <a href="{% url 'exercises:add_exercise' %}">Add exercise</a>
                {% endif %}
                <a href="{% url 'exercises:exercise_list' category='CT' %}">Chest</a>
                <a href="{% url 'exercises:exercise_list' category='SH' %}">Shoulder</a>
                <a href="#">Back</a>
                <a href="#">Biceps</a>
                <a href="#">Triceps</a>
                <a href="#">Abs</a>
                <a href="#">Legs</a>
            </div>
        </div>    
    </div>
    


    {% if request.user.is_authenticated %}
        <div class="user-dropdown-container">
            <button class="user-btn"><i class="fa-solid fa-user"></i></button>
                <div class="user-dropdown-content">
                    <a href="{% url 'workouts:custom_workouts_list' %}">My workouts</a>
                    <a href="{% url 'accounts:profile-details' user.id %}">My profile</a>
                    <form method="post" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="logout-btn">LOG OUT</button>
                    </form>
                </div>
        </div>
    {% else %}
        <div class="user-btn-ua">
            <a href="{% url 'accounts:login' %}">LOG IN</a>
        </div>
    {% endif %}
</nav>

templates/profile_page.html
{% extends 'base.html' %}

{% block title %}My profile{% endblock %}

{% block content %}
    <section>
        {% if user.profile %}
            <div class="profile-img-container">
                    <img src="{{ user.profile.image }}" alt="This is the profile picture of this user.">
                    <h3>{{ user.profile.first_name }} {{ user.profile.last_name }}</h3>
                    <div class="profile-menu">
                        <i class="fa-solid fa-bars"></i>
                        <div class="profile-menu-dropdown">
                            <a href="{% url 'accounts:update_profile' user.id %}" class="update-profile-btn">Update your profile</a>
                            <a href="{% url 'accounts:delete_account' user.id %}" class="delete-profile-btn">Delete Profile</a>
                        </div>
                    </div>
            </div>
            <div class="profile-details">
                <p><span>Age:</span> {{ user.profile.age }}</p>
                <p><span>Height:</span> {{ user.profile.height }}</p>
                <p><span>Weight:</span> {{ user.profile.weight }}</p>
                <p><span>Goal:</span> {{ user.profile.get_goal_display }}</p>
                <p><span>Calories need:</span> {{ user.profile.calories_needed }}</p>
            </div>
        {% else %}
            <div class="no-profile">
                <p>You don't have a personal profile yet!</p>
                <a href="{% url 'accounts:configure-profile' user.id %}" class="profile-conf-btn">Configure one now!</a>
            </div>
        {% endif %}
    </section>
{% endblock %}