workoutPlanner/forum/urls.py
from django.urls import path, include

from workoutPlanner.forum import views
from workoutPlanner.forum.views import PostListCreateAPIView

app_name = 'forum'
urlpatterns = [
    path('', include([
        path('', views.PostListView.as_view(), name='post_list'),
        path('<int:pk>/', include([
            path('', views.PostDetailView.as_view(), name='post_detail'),
            path('edit/', views.PostUpdateView.as_view(), name='post_update'),
            path('delete/', views.PostDeleteView.as_view(), name='post_delete'),
            path('comment/', views.AddCommentView.as_view(), name='add_comment'),
        ])),
    ])),

]

workoutPlanner/urls.py
from django import core
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('workoutPlanner.forum.api_urls')),
    path('', include([
        path('', include('workoutPlanner.common.urls')),
        path('accounts/', include('workoutPlanner.accounts.urls')),
        path('exercises/', include('workoutPlanner.exercises.urls')),
        path('workouts/', include('workoutPlanner.workouts.urls')),
        path('forum/', include('workoutPlanner.forum.urls')),
    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workoutPlanner/forum/models.py
from audioop import reverse

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

from workoutPlanner.forum.choices import Status

UserModel = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Status.PUBLISHED)


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        related_name='forum_posts',
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT,
    )
    objects = models.Manager()
    published = PublishedManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

workoutPlanner/forum/forms.py
from workoutPlanner.forum.models import Post, Comment

from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Search...',
                'class': 'search-bar',
            }
        ),
        required=False,
        label='',
    )

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
        labels = {
            'title': '',
            'body': ''
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Post title...',}),
            'body': forms.Textarea(attrs={'placeholder': 'Share your thoughts...'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': ''
        }
        widgets = {
            'body': forms.Textarea(attrs={'placeholder': 'Write a comment...'})
        }

workoutPlanner/forum/views.py
from webbrowser import Error

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.views import APIView

from workoutPlanner.forum.forms import CreatePostForm, CommentForm, SearchForm
from workoutPlanner.forum.models import Post, Comment


class PostListView(LoginRequiredMixin, ListView, FormMixin):
    login_url = reverse_lazy('accounts:login')
    form_class = SearchForm
    template_name = 'forum/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.all()
        form = self.form_class(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            if query:
                queryset = queryset.filter(body__icontains=query)

        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('accounts:login')
    model = Post
    context_object_name = 'post'
    template_name = 'forum/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.filter(active=True)
        context['form'] = CommentForm()
        return context

# class PostCreateView(LoginRequiredMixin, CreateView):
#     login_url = reverse_lazy('accounts:login')
#     model = Post
#     context_object_name = 'post'
#     form_class = CreatePostForm
#     template_name = 'forum/add_post.html'
#
#     def form_valid(self, form):
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = self.request.user
#             post.slug = slugify(post.title)
#             post.save()
#
#         return redirect('forum:post_list')

from rest_framework import generics, permissions
from .models import Post
from .serializers import PostSerializer
from django.utils.text import slugify
from django.utils import timezone

class PostListCreateAPIView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(
            author=self.request.user,
            slug=slugify(self.request.data.get('title')),
            publish=timezone.now()
        )

class PostDetail(APIView):
    def get_object(self, pk):
        try:
            return Post.objects.get(pk=pk)
        except Post.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        post = self.get_object(pk=pk)
        serializer = PostSerializer(post)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        post = self.get_object(pk=pk)
        serializer = PostSerializer(post, data=request.data)
        if serializer.is_valid():
            serializer.save(
                author=self.request.user,
                slug=slugify(self.request.data.get('title')),
                publish=timezone.now()
            )
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        post = self.get_object(pk=pk)
        post.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'forum/post-update.html'
    form_class = CreatePostForm

    def get_success_url(self):
        return reverse_lazy('forum:post_detail', kwargs={'pk': self.object.pk})

    def get_initial(self):
        initial = super().get_initial()
        initial['title'] = self.object.title
        initial['body'] = self.object.body

        return initial


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('forum:post_list')
    template_name = 'forum/delete-post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CreatePostForm(instance=self.object)
        for field in form.fields.values():
            field.widget.attrs['disabled'] = True
        context['form'] = form

        return context

class AddCommentView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = Comment
    form_class = CommentForm
    template_name = 'forum/add_comment.html'

    def form_valid(self, form):
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Post, pk=self.kwargs['pk'])
            comment.name = self.request.user.username
            comment.email = self.request.user.email
            comment.save()

            return redirect('forum:post_detail', pk=self.kwargs['pk'])

# class CommentViewSet(viewsets.ModelViewSet):
#     queryset = Comment.objects.all()
#     serializer_class = CommentSerializer
#
#     def get(self):
#         pass

templates/forum/add_comment.html
{% extends 'base.html' %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{% url 'forum:post_detail' pk=post.pk %}">Back to the post</a></p>
    {% else %}
        {% include 'forum/add_comment.html' %}
    {% endif %}
{% endblock %}

templates/forum/add_post.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock %}

{% block content %}
    <button id="show-add-post-btn">Add Post</button>

    <div id="add-post-form">
        <form>
            <input type="text" id="post-title" placeholder="Post title">
            <textarea id="post-body" placeholder="Post body" rows="4"></textarea>
            <button id="submit-post">Post</button>
            <button id="hide-form-btn">Hide</button>
        </form>
    </div>
{% endblock %}

templates/forum/comment_form.html
<div class="comment-form-container">
    <h2>Add a new comment</h2>
    <form action="{% url 'forum:add_comment' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Share</button>
    </form>
</div>

templates/forum/delete-post.html
{% extends 'base.html' %}

{% block title %}Delete post{% endblock %}

{% block content %}
    <div class="delete-post-form-container">
        <h1>Delete post</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="delete-post-btn">Delete</button>
        </form>
    </div>
{% endblock %}

templates/forum/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/forum/post-update.html
{% extends 'base.html' %}

{% block title %}Edit post{% endblock %}

{% block content %}
    <div class="delete-post-form-container">
        <h1>Edit post</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="delete-post-btn">Edit</button>
        </form>
    </div>
{% endblock %}

templates/forum/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="post-detail-container">
        <div class="post-body">
            <h1>{{ post.title }}</h1>
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>
            <div class="post-content">
                {{ post.body|linebreaks }}
            </div>
        </div>
        <div class="comments-container">
            {% with comments.count as total_comments %}
                <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
            {% endwith %}
            {% for comment in comments %}
                <div class="comment">
                     <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
                     <p class="comment-content">{{ comment.body|linebreaks }}</p>
                </div>
            {% empty %}
                <p>There are no comments.</p>
            {% endfor %}
        </div>
    </div>
    {% include 'forum/comment_form.html' %}
{% endblock %}

templates/forum/post_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}WorkoutPlanner's Forum{% endblock%}

{% block content %}
    <div class="post-list-container">
        <h1>Welcome to our forum</h1>
        <div class="forum-header">
            <div class="search-form-container">
                <form method="get">
                    {{ form }}
                    <button><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>
        <button id="show-add-post-btn">Add Post</button>

        <div id="add-post-form">
            <input type="text" id="post-title" placeholder="Post title">
            <textarea id="post-body" placeholder="Post body" rows="4"></textarea>
            <button id="submit-post">Post</button>
            <button id="hide-form-btn">Hide</button>
        </div>
        {% if posts %}
            {% for post in posts %}
                <div id="post-list">
                    <div class="post-container">
                        <h2>
                            <a href="{% url 'forum:post_detail' pk=post.pk %}">
                                {{ post.title }}
                            </a>
                            {% if user.id == post.author_id or user|has_perm:'forum.change_post' %}
                                <div class="post-options-container">
                                    <i id='post-options-icon' class="fa-solid fa-caret-down"></i>
                                    <div class="options-content">
                                        <button class="edit-post">Edit</button>
                                        <button class="delete-post" data-post-id="{{ post.id }}">Delete</button>
                                    </div>
                                </div>
                            {% endif %}
                        </h2>
                        <p class="date">
                            Published {{ post.publish }} by {{ post.author }}
                        </p>
                        <div class="content">
                            {{ post.body|truncatewords:30|linebreaks }}
                        </div >
                    </div>
                </div>
            {% endfor %}
            {% include 'forum/pagination.html' %}
        {% else %}
            <p>There are no posts yet!</p>
        {% endif %}
    </div>
{% endblock %}